
.SUFFIXES: .c .s

TARGET_LIB=libc.a



C_SRC = mem.c         \
        printf.c      \
        string.c      \
        ctype.c       



include $(ROOT)/common.mk

# targets




build:	build_lib

	
-include .dep

