
.SUFFIXES: .c .s

TARGET_LIB=libdrvarch.a


C_SRC = video/video.c   \
        kbd/keyb.c      \
        std/std.c      
				
         	    

include $(ROOT)/common.mk




build:	build_lib 
	
-include .dep

